services:
  # Web Service
  - type: web
    name: venus-recipe-system
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DB_PATH
        value: ./data/venus_recipe.db

    # Auto-deploy configuration
    autoDeploy: true

    # Health check
    healthCheckPath: /

    # Instance settings
    numInstances: 1
    disk:
      name: data
      mountPath: ./data
      sizeGB: 1